In [6]:
import numpy as np

In [7]:
np.random.random()

0.6336482349262754

In [9]:
np.random.seed(10)
np.random.random()

0.771320643266746

In [10]:
np.random.uniform(5,80)

6.5563962019551125

In [12]:
np.random.uniform(5,80,10).reshape(5,2)

array([[ 5.29611997, 43.41441975],
       [65.94657212, 50.93945501],
       [59.13164881, 26.89070511],
       [73.83305919, 58.59318375],
       [45.6908276 , 15.66275357]])

In [13]:
np.random.randint(5,80,10).reshape(5,2)

array([[18, 35],
       [35, 17],
       [70, 36],
       [62, 41],
       [32, 23]])

In [23]:
a = np.random.randint(5,80,10)
a

array([47, 62, 55, 50, 45, 78, 42,  5, 23, 28])

In [24]:
np.max(a)

78

In [25]:
np.min(a)

5

In [26]:
np.argmax(a)

5

In [27]:
b = np.random.randint(5,80,10)
b

array([ 8, 34, 21, 19, 56, 22, 55, 58, 30, 53])

In [28]:
b[b%2==0]=-1
b

array([-1, -1, 21, 19, -1, -1, 55, -1, -1, 53])

In [29]:
c = np.random.randint(5,70,10)
c

array([22, 37, 46, 17, 35, 22, 21,  5, 36, 69])

In [31]:
np.where(c%2==0,-1,c)

array([-1, 37, -1, 17, 35, -1, 21,  5, -1, 69])

In [32]:
d = np.random.randint(5,50,10)
d

array([43, 27, 37,  7,  8, 36, 40, 32, 23, 18])

In [35]:
e = np.sort(d)

In [36]:
np.percentile(e,25)

19.25

In [38]:
np.percentile(e,100)

43.0