In [1]:
import numpy as np

In [3]:
arr1 = np.arange(24).reshape(6,4)

In [6]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
arr1[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

**` Indexing using Boolean Array`**

In [8]:
arr2 = np.random.randint(1,100,20).reshape(4,5)

In [9]:
arr2

array([[47, 15, 41,  6, 14],
       [95,  5, 87, 26, 54],
       [89, 93, 13, 29, 26],
       [35, 92, 64, 92, 41]])

In [10]:
arr2>50

array([[False, False, False, False, False],
       [ True, False,  True, False,  True],
       [ True,  True, False, False, False],
       [False,  True,  True,  True, False]])

In [12]:
arr2[arr2>50]

array([95, 87, 54, 89, 93, 92, 64, 92])

In [13]:
arr2[(arr2>50) & (arr2%2 != 0)]

array([95, 87, 89, 93])

In [14]:
arr2[(arr2>50) & (arr2%2 != 0)]=0

In [16]:
arr2

array([[47, 15, 41,  6, 14],
       [ 0,  5,  0, 26, 54],
       [ 0,  0, 13, 29, 26],
       [35, 92, 64, 92, 41]])