In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([8,7,6,5,4,3,2,1])

In [6]:
arr1.dot(arr2)

120

In [4]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [5]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

**Ravel Method**

In [8]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [9]:
for i in np.nditer(arr4):
  print(i)

6
7
8
9
10
11


**Transpose**

In [10]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

**Stacking**

In [12]:
arr5 = np.arange(12,18).reshape(2,3)

In [14]:
np.hstack((arr3,arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [15]:
np.vstack((arr3,arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

**Splitting**

In [18]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
np.vsplit((arr3),2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]