In [1]:
import numpy as np

In [3]:
arr1 = np.arange(24)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [5]:
arr2 = arr1.reshape(6,4)

In [6]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

**Slicing Operation**

In [12]:
arr2[3:5,2:4]

array([[14, 15],
       [18, 19]])

In [13]:
arr2[4:6,2:4]

array([[18, 19],
       [22, 23]])

**Iteration**

In [14]:
for i in arr2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [15]:
for i in np.nditer(arr2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
